### ISSUE TITLE
求总结项目开发过程中git的操作规范

### ISSUE THREAD

**Issue by ArronSeven** [Darrenzzy/pro-guide#2]
比如：什么时候应该新建分支，什么时候打tag，什么时候需要把发布到 release ， 修复bug时怎么合理的建分支。
还有包括版本号的说明也可以出一个（虽然网上已经很多了）

**Comment by Darrenzzy** [comment]
本仓库提供的是实际开发中遇到的问题，以及解决方案。 基础命令可以网上搜到，且很快得到解决。

比如解决了以下实际中操作git遇到的问题：
1. 当提交commit 文案写错了，如何纠正后提交且 错误的文案无记录
2. 计划将修改bug的某个分支中 指定文件合并到当前分支 
3. 将远程代码pull后，对本地开发分支没有merge记录，类似rebase方案
4. 将指定文件回退到 指定分支的指定 commit id，这个使用评率非常高
5. 本地项目期望提交到多个管理仓库的配置方案
6. 快速找到远程和本地 的最新分支
7. 查看当前已经提交但是还未push 的代码diff
8. 撤销本地所有更改，到原始状态，包括去除目录下的 .XXX文件
9. 查看历史提交记录，对应快捷键和搜索

**Comment by Darrenzzy** [comment]
如若需要可以指出对应项，我会专门写到博客中，方便更多人阅读到。  当前仓库中用于 开发过程中快速索引查询。
